FROM debian:sid-slim AS builder
WORKDIR /src

RUN apt-get update && apt-get install -y cmake ninja-build g++ git libssl-dev liburing-dev

COPY . .

RUN cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build --target Api

FROM debian:sid-slim
WORKDIR /app

RUN apt-get update && apt-get install -y libssl3 liburing2 ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /src/build/Api /app/Api

ENV LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
ENTRYPOINT ["/app/Api"]