services:
  api1:
    image: seu_usuario/rinha-api:latestt
    command: ["/sockets/api1.sock"]
    volumes:
      - shared-sockets:/sockets
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "165MB"

    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

  api2:
    image: seu_usuario/rinha-api:latest
    command: ["/sockets/api2.sock"]
    volumes:
      - shared-sockets:/sockets
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "165MB"

    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

  loadbalancer:
    image: seu_usuario/rinha-lb:latest
    ports:
      - "9999:9999"
    volumes:
      - shared-sockets:/sockets
    networks:
      - rinha-network
    depends_on:
      - api1
      - api2
    entrypoint: ["/bin/sh", "-c", "sleep 10 && /app/LoadBalancer"]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

networks:
  rinha-network:
    driver: bridge

volumes:
  shared-sockets: