services:
  api1:
    image: rinha-api:latest
    command: ["/sockets/api1.sock"]
    volumes:
      - shared-sockets:/sockets
      - ./data:/data
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "165MB"
    build:
      context: .
      dockerfile: Dockerfile.api
    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

  api2:
    image: rinha-api:latest
    command: ["/sockets/api2.sock"]
    volumes:
      - shared-sockets:/sockets
      - ./data:/data
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "165MB"
    depends_on:
      - api1
    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

  loadbalancer:
    image: rinha-lb:latest
    ports:
      - "9999:9999"
    volumes:
      - shared-sockets:/sockets
    networks:
      - rinha-network
    depends_on:
      - api1
      - api2
    entrypoint: ["/bin/sh", "-c", "sleep 10 && /app/LoadBalancer"]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
    build:
      context: .
      dockerfile: Dockerfile.lb
    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

networks:
  rinha-network:
    driver: bridge

volumes:
  shared-sockets: