FROM debian:bookworm-slim
WORKDIR /app

COPY ./build/Api /app/Api
COPY ./build/_deps/hermes-build/libhermes.so /usr/lib/libhermes.so

ENV LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
ENTRYPOINT ["/app/Api"]